In [1]:
import requests 
import pandas as pd
import json 

API_KEY = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6ImNjMTgwOGMyLTIzNTEtNDFhNS04Y2MxLWM0ZDVjYTRhYjA3NCIsImlhdCI6MTc2MTM5NTYxMSwic3ViIjoiZGV2ZWxvcGVyLzMwNzIzMzE2LTAzOWYtNTZjZC0wNTRhLTUxNWQxMjZkYTk4NiIsInNjb3BlcyI6WyJyb3lhbGUiXSwibGltaXRzIjpbeyJ0aWVyIjoiZGV2ZWxvcGVyL3NpbHZlciIsInR5cGUiOiJ0aHJvdHRsaW5nIn0seyJjaWRycyI6WyIyMTIuMTc4LjgxLjI2Il0sInR5cGUiOiJjbGllbnQifV19.pzsbxyJgwgNBORe_UhkClvSI6-NOVAJKDpjmnSnWfOFzXfiQmUUuCJN9buiYeKv9rVpRmLyoeleGYX1IxNHBkg"

PLAYER_TAG = "%23CUY0U8C9P"  # %23 = #

headers = {"Authorization": f"Bearer {API_KEY}"}

url = f"https://api.clashroyale.com/v1/players/{PLAYER_TAG}"

response = requests.get(url, headers=headers)
player_data = response.json()

c:\Users\matek_yulq090\anaconda3\envs\Env1\Lib\site-packages\requests\__init__.py:86: RequestsDependencyWarning: Unable to find acceptable character detection dependency (chardet or charset_normalizer).
  warnings.warn(

In [2]:
player_info = {
    'tag': player_data.get('tag'),
    'name': player_data.get('name'),
    'expLevel': player_data.get('expLevel'),
    'trophies': player_data.get('trophies'),
    'bestTrophies': player_data.get('bestTrophies'),
    'wins': player_data.get('wins'),
    'losses': player_data.get('losses'),
    'battleCount': player_data.get('battleCount'),
    'threeCrownWins': player_data.get('threeCrownWins'),
    'challengeCardsWon': player_data.get('challengeCardsWon'),
    'challengeMaxWins': player_data.get('challengeMaxWins'),
    'tournamentCardsWon': player_data.get('tournamentCardsWon'),
    'tournamentBattleCount': player_data.get('tournamentBattleCount'),
    'role': player_data.get('role'),
    'donations': player_data.get('donations'),
    'donationsReceived': player_data.get('donationsReceived'),
    'totalDonations': player_data.get('totalDonations'),
    'warDayWins': player_data.get('warDayWins'),
    'clanCardsCollected': player_data.get('clanCardsCollected'),
    'clan_tag': player_data.get('clan', {}).get('tag'),
    'clan_name': player_data.get('clan', {}).get('name'),
    'clan_badgeId': player_data.get('clan', {}).get('badgeId'),
    'arena_id': player_data.get('arena', {}).get('id'),
    'arena_name': player_data.get('arena', {}).get('name'),
    'starPoints': player_data.get('starPoints'),
    'expPoints': player_data.get('expPoints'),
}

df_player_info = pd.DataFrame([player_info])

In [ ]:
all_cards_data = []
for card in player_data.get('cards', []):
    card_info = {
        'card_name': card.get('name'),
        'card_id': card.get('id'),
        'level': card.get('level'),
        'maxLevel': card.get('maxLevel'),
        'starLevel': card.get('starLevel'),
        'evolutionLevel': card.get('evolutionLevel'),
        'maxEvolutionLevel': card.get('maxEvolutionLevel'),
        'rarity': card.get('rarity'),
        'count': card.get('count'),
        'elixirCost': card.get('elixirCost'),
    }
    all_cards_data.append(card_info)

df_all_cards = pd.DataFrame(all_cards_data)

âœ“ All Cards DataFrame: (119, 10)
  card_name   card_id  level  maxLevel  starLevel  evolutionLevel  \
0    Knight  26000000      9        14        NaN             NaN
1   Archers  26000001     12        14        NaN             1.0
2   Minions  26000005     10        14        NaN             NaN
3    Arrows  28000001     13        14        NaN             NaN
4  Fireball  28000000      7        12        NaN             NaN

   maxEvolutionLevel  rarity  count  elixirCost
0                1.0  common   2680         3.0
1                1.0  common    756         3.0
2                NaN  common    504         3.0
3                NaN  common    890         3.0
4                NaN    rare    343         4.0

In [6]:
current_deck_data = []
for card in player_data.get('currentDeck', []):
    card_info = {
        'card_name': card.get('name'),
        'card_id': card.get('id'),
        'level': card.get('level'),
        'maxLevel': card.get('maxLevel'),
        'starLevel': card.get('starLevel'),
        'evolutionLevel': card.get('evolutionLevel'),
        'maxEvolutionLevel': card.get('maxEvolutionLevel'),
        'rarity': card.get('rarity'),
        'count': card.get('count'),
        'elixirCost': card.get('elixirCost'),
    }
    current_deck_data.append(card_info)

df_current_deck = pd.DataFrame(current_deck_data)

In [7]:
df_current_deck

,card_name,card_id,level,maxLevel,starLevel,evolutionLevel,maxEvolutionLevel,rarity,count,elixirCost
0,Valkyrie,26000011,10,12,NaN,1.0,1.0,rare,471,4
1,Musketeer,26000014,13,12,2.0,1.0,1.0,rare,0,4
2,Spear Goblins,26000019,14,14,NaN,NaN,NaN,common,30818,2
3,Arrows,28000001,13,14,NaN,NaN,NaN,common,890,3
4,Skeleton Army,26000012,10,9,3.0,NaN,1.0,epic,0,3
5,Boss Bandit,26000103,3,4,NaN,NaN,NaN,champion,5,6
6,Firecracker,26000064,12,14,NaN,NaN,1.0,common,2984,3
7,Mini P.E.K.K.A,26000018,10,12,NaN,NaN,NaN,rare,207,4